import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'cad_gfsilva' at '6/13/16 5:58 PM' with Gradle 2.11
 *
 * @author cad_gfsilva, @date 6/13/16 5:58 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
